#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install git curl
git clone https://github.com/webzorg/google-api-automation.git

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.4.1

source .profile
rvm -v
ruby -v

mv ~/google-api-automation/install/.gemrc ~/

gem install google-api-client
gem install googleauth
gem install signet
gem install json
gem install selenium-webdriver
gem install pp

mkdir -p ~/bin
tar -xvzf google-api-automation/install/geckodriver-v0.16.1-linux64.tar.gz -C ~/bin/
tar -xjf google-api-automation/install/firefox-55.0a1.en-US.linux-x86_64.tar.bz2 -C ~/bin/
ln -s firefox/firefox bin/firefox-nightly

source .profile
